name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
    contents: write

jobs:
    publish-web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - run: npm i
            - run: npm test

            - name: Set build version
              run: ./tools/build-version.sh $GITHUB_REF_NAME

            - name: Build Nethack Web
              run: npm run build:web

            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                   folder: build
            
            - run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
            - run: echo "prev_tag=$(git tag | sort --version-sort | tail -n2 | head -1)" >> $GITHUB_ENV
            - run: npm ci && npm run changelog -- -t ${{env.prev_tag}}..${{env.latest_tag}}
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                body_path: CHANGELOG.md
                prerelease: false

